### ISSUE TITLE
Transaction処理について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Comments#4]
NetCommons3/ContentComments#18

**Comment by s-nakajima** [comment]
BehaviorのbeforeSaveに移動したことで、呼び出し元でTransactionを開始することになったため、Closeする

https://github.com/NetCommons3/Comments/commit/5126d30e98fe6f1f65f0d372619d9ae99c34b562

**Comment by s-nakajima** [comment]
WorkflowCommentBehaviorに移動
