### ISSUE TITLE
Commentsテーブルのcontent_key

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Comments#5]
コメントは複数言語が混在して表示される話で決定してましたっけ？（ContentCommentsも同じ）
一度話した記憶があります。
議事録検索してみたがヒットせず。
再確認のため書いときます。

**Comment by kteraguchi** [comment]
以前話した時は、ブログ等のコメント（ContentCommentsプラグイン）についてだった気がします。
それについては、複数言語が混在するという話だったと記憶しています。
承認コメント（Commentsプラグイン）については、改めて確認必要。

**Comment by s-nakajima** [comment]
私の記憶では、複数言語が混在して表示する話で決定したと思ってます。
