### ISSUE TITLE
Behaviorの利用

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Comments#6]
Behaviorを作成し、各プラグインの負担を減らした方が良いと思います。
参考：Tagsプラグイン

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Comments/commit/255bfe93975ca189bf8b444e6d32a1b0d098f3b1#diff-a559b87068921eec05086ce5485e9784

**Comment by s-nakajima** [comment]
WorkflowCommentBehaviorに移動
